### ISSUE TITLE
oracle 11g R2数据库报错

### ISSUE THREAD

**Issue by fengwenyi** [fengwenyi/mybatis-plus-code-generator#17]
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)

**Comment by jwister** [comment]
我也碰到了这个问题 应该是oracle驱动版本的问题 拉源码自己改吧

**Comment by jwister** [comment]
您的邮件已收到，谢谢。
