### ISSUE TITLE
docker环境下，生成失败

### ISSUE THREAD

**Issue by CherryRum** [fengwenyi/mybatis-plus-code-generator#26]
docker环境下，日志提示生成成功，但是输出目录是空白

**Comment by fengwenyi** [comment]
> 

1、首先看一下你的docker部署命令。

比如，示例命令：

```shell
docker run -d -p 8899:8899 --name code-generator -v ~/temp:/temp fengwenyi/mybatis-plus-code-generator:3.5.2.1
```

其中 `-v ~/temp:/temp` 表示：主机目录就是 `~/temp`，docker的目录是`/temp`。

因为 服务默认的目录是 `/temp`，因此，默认生成的目录就是在docker容器中的 `/temp` 下面。

如果你更改了，在主机目录就找不到了。

2、界面上不要再更改目录。

如果是 docker部署，页面上的目录，就不要填写了

因为是映射的 temp，修改了，就可能导致找不到了

**Comment by CherryRum** [comment]
我试试
